// <auto-generated />
using JEMP_API_HeyGIA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JEMP_API_HeyGIA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250817205602_MakeColorNullable")]
    partial class MakeColorNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("JEMP_API_HeyGIA.Modelos.Apuesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RuletaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RuletaId");

                    b.ToTable("Apuestas");
                });

            modelBuilder.Entity("JEMP_API_HeyGIA.Modelos.Ruleta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstaAbierta")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Ruletas");
                });

            modelBuilder.Entity("JEMP_API_HeyGIA.Modelos.Apuesta", b =>
                {
                    b.HasOne("JEMP_API_HeyGIA.Modelos.Ruleta", "Ruleta")
                        .WithMany("Apuestas")
                        .HasForeignKey("RuletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ruleta");
                });

            modelBuilder.Entity("JEMP_API_HeyGIA.Modelos.Ruleta", b =>
                {
                    b.Navigation("Apuestas");
                });
#pragma warning restore 612, 618
        }
    }
}
